### ISSUE TITLE
Issue Templates 적용 검토

### ISSUE THREAD

**Issue by raylee2209** [eGovFramework/egovframe-docs#220]
다양한 오픈소스 프로젝트에서 효율적으로 문서를 관리하기 위해 다양한 도구나 프로세스를 적용하고 있습니다. 

표준프레임워크도 DokuWiki 기반 가이드 문서를 전환하기 위한 다양한 의견과 markdown 으로 관리하더라도 
통일성있고 문서로 자동 변환하거나 향후 가이드 사이트 구축을 하기위해 다양한 제안, 아이디어, 개선사항 등을 검토해서 반영하면 좋을 것 같습니다. 

먼저 egovframe-docs 프로젝트도 이슈 템플릿을 적용해서 요청 사항(필요한 정보 포함)을 관리하면 좋을 것 같습니다.

**Comment by eGovFrameSupport** [comment]
내년도 Contribution egovframe-docs에는 이슈 템플릿을 적용을 긍정적으로 검토하겠습니다.
좋은 의견 감사드립니다.
