### ISSUE TITLE
PR Template 검토 

### ISSUE THREAD

**Issue by raylee2209** [eGovFramework/egovframe-docs#223]
Markdown은 동일한 표현 방식을 여러 방법으로 기술할 수 있어
현재 실행환경 가이드도 작성하는 사람에 따라 조금씩 다르게 작성/변환되고 있습니다. 
( 예를 들어 링크가 기존 가이드 문서로 되어 있거나 링크, 이미지, 강조 등 서로 방식을 다르게 작성 등)

현재 PR Template이 적용되고 있지 않은데 기본적인 표프 가이드의 그라운드룰을 안내하고 
준수하고 있는지 하는 프로세르를 적용하는 것도 좋을 것 같습니다.  
(PR 시 적용할 그라운드룰을 요청 받는 것도 좋을 것 같습니다)

**Comment by eGovFrameSupport** [comment]
PR 전에 몇 가지 확인 사항 및 그라운드룰에 대한 템플릿을 적용하면 여러 PR들이 더 통일성과 완결성을 갖출 것으로 기대됩니다.
내년도 Contribution egovframe-docs에는 이슈 템플릿을 적용을 긍정적으로 검토하겠습니다.
좋은 의견 감사드립니다.
