### ISSUE TITLE
리포지토리에 라이선스 추가/등록

### ISSUE THREAD

**Issue by raylee2209** [eGovFramework/egovframe-docs#230]
깃허브에서는 리포지토리에 사용, 배포, 수정, 복제 등의 권리를 명시하도록 가이드하고 있습니다. 
라이선스가 없다면 기본저작권법이 적용되므로 파생물을 복제, 배포 또는 생성할 수 없습니다. 

- 참고 : https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

오픈소스 프로젝트의 문서는 보통 코드로 문서를 관리(Docs as Code)하므로 일반적으로 CC 라이선스와 code 라이선스(MIT 라이선스 등)도 같이 적용하기도 합니다.   

[egovframe-docs](https://github.com/eGovFramework/egovframe-docs) 리포지토리도 라이선스 적용이 필요합니다.

- 참고 : [About CC Licenses](https://creativecommons.org/share-your-work/cclicenses/)

**Comment by eGovFrameSupport** [comment]
egovframe-docs에도 MIT 라이선스 명시가 필요함에 동의합니다.
좋은 의견 감사드립니다.
