### ISSUE TITLE
가이드 문서 작성 규칙 중 파일명 규칙에 대한 추가 내용이 제시되면 좋겠습니다.

### ISSUE THREAD

**Issue by HR2491** [eGovFramework/egovframe-docs#308]
안녕하세요.

eGovFramework/egovframe-docs 리포지토리의 README 에서는 [전자정부 표준프레임워크 가이드 작성 방법](https://github.com/eGovFramework/egovframe-docs?tab=readme-ov-file#%EC%A0%84%EC%9E%90%EC%A0%95%EB%B6%80-%ED%91%9C%EC%A4%80%ED%94%84%EB%A0%88%EC%9E%84%EC%9B%8C%ED%81%AC-%EA%B0%80%EC%9D%B4%EB%93%9C)에 대해 소개하고 있습니다.

이 내용 중 [문서 작성 규칙](https://github.com/eGovFramework/egovframe-docs?tab=readme-ov-file#%EB%AC%B8%EC%84%9C-%EC%9E%91%EC%84%B1-%EA%B7%9C%EC%B9%99) 을 보면 **파일명은 소문자와 하이픈(-)을 사용**하라고 안내되어 있는데요.

실제 풀리퀘스트 리뷰 시에는 파일명에 언더바(_)도 넣어서 작성하도록 안내([배치처리 > Logback logging 문서 수정 #296](https://github.com/eGovFramework/egovframe-docs/pull/296))되고 있고, 
현재까지 작성된 파일들도 하이픈과 언더바가 혼용되어 있습니다.

개인적인 생각이지만 혼용하여 작성하는 분들은 
- 상위 제목 작성시 : 하이픈
- 상위에 속한 하위 제목 작성시 : 언더바

로 의도한 것이 아닐까 싶습니다. 
이렇게 작성된 파일들을 폴더와 함께 모아보면 직관적으로 계층을 알 수 있어 좋더라구요.

때문에 파일명 작성시 어떤 경우 언더바를 넣어야 하는지 추가 내용이 제시 된다면 
좀 더 일괄적이고 직관적인 파일명을 얻을 수 있을 것 같습니다.

감사합니다.

**Comment by eGovFrameSupport** [comment]
최초 Contribution시 문서간 상하위 계층의 문제를 인지하지 못했고, 그로 인해 참여자분들에게 적절한 가이드가 제공되지 않았습니다.
그래서 batch-layer에 대해서는 참여자님께서 이해하신 대로 임시 가이드를 하였습니다.
내년도 Contribution에는 문서간 상하위 계층 문제에 대해 폴더 방식을 적용할지 혹은 위와 같은 파일명 방식을 적용할지 또는 다른 방식을 적용할지에 대한 결론을 내린 후 진행할 예정입니다.
혼란을 드린 점 사죄드리고, 좋은 의견 감사드립니다.
