### ISSUE TITLE
Contributing 가이드 작성/추가

### ISSUE THREAD

**Issue by raylee2209** [eGovFramework/egovframe-docs#327]
[egovframe-docs](https://github.com/eGovFramework/egovframe-docs) 리포지토리(README) 에 Contributing 가이드가 작성되면 좋을 것 같습니다. 

Contributing 가이드는 깃허브에서 권장하고 있는 커뮤니티 표준([Community Standards](https://github.com/eGovFramework/egovframe-docs/community))으로 Community Standards는 Insights > Community Standards에서 확인할 수 있습니다. 

현재 [eGovFramework](https://github.com/eGovFramework) 실행환경 리포지토리에는 https://github.com/eGovFramework/egovframe-runtime/wiki 에 일부 Contributing 가이드 내용이 있으나 이 부분의 가이드를 업데이트하는 방법도 있으나 리포지토리의 최상단에 CONTRIBUTING.md 파일을 생성해 해당 프로젝트의 컨트리뷰션 가이드를 제공하는 것이 일반적입니다. 

CONTRIBUTING.md 에는 주로 컨티리뷰션하는 방법인 이슈 정책, 생성, 라이프사이클에 대한 내용과 PR하는 방법(Contributor License Agreement 포함), 커밋 그라운드룰 등등을 제공하고 있습니다.

**Comment by eGovFrameSupport** [comment]
좋은 의견 감사드립니다.
Contributing.md 파일을 통해 PR방법 등을 안내하면 긍정적인 효과가 있을 것으로 보입니다.
매번 다양한 정보에 대해 안내해주시는 점에 대해 깊이 감사드립니다.
