### ISSUE TITLE
간단한 챗봇 기능 및 화면 도입이 가능한지 검토 문의드립니다.

### ISSUE THREAD

**Issue by kwonhyuck0218** [eGovFramework/egovframe-docs#337]
안녕하세요

간단한 챗봇 기능도입이 가능한지 문의드립니다.

요즘 모든 홈페이지에서 거의 챗봇을 도입하고 있습니다.

당연히 자연어처리, AI 등이 들어간 챗봇은 따로 구현해서 써야겠지만 이 부분은 각자 따로 개발하더라도

간단한 챗봇 기능 및 화면정도 있으면 좋을 것 같습니다.

가능하다면 FAQ 데이터와 연동되면 좋을 것 도 같습니다.

**Comment by eGovFrameSupport** [comment]
안녕하세요
전자정부 표준프레임워크 센터입니다.

'24년 7월 29일부터 9월 30일까지 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2024년 전자정부 표준프레임워크 컨트리뷰션"을 개최 하였습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며,  전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다. 
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.

앞으로도 전자정부 표준프레임워크에 지속적인 관심 바라오며, 아래 URL 접속, 설문지로 이동하여 항목에 응답 부탁드립니다.
https://forms.gle/6qRXGFZn5WTaxBCK8

※ 컨트리뷰션 종료 후, 시상관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

**Comment by eGovFrameSupport** [comment]
좋은 의견 감사드립니다.
표준프레임워크 새로운 버전에서 챗봇 도입에 대한 내부 검토를 진행해 보겠습니다. 
다만 질의해주신 내용은 egovframe-docs와 무관한 내용이므로, Close 하겠습니다.
감사합니다.
