### ISSUE TITLE
egovfroame-runtime의 여러 layer 내용 보강 필요

### ISSUE THREAD

**Issue by likiwook** [eGovFramework/egovframe-docs#342]
egovfroame-runtime의 foundation-layer중 일부 문서에는 내용이 일부만 반영되어 있어서 
보강이 필요합니다.
즉, 특징,장점,사용방법등의 보강이 필요합니다.

**Comment by eGovFrameSupport** [comment]
좋은 의견 감사드리고, property.md(#399 ), web-servlet.md(#402 ) 파일에 대해 특징, 장점, 사용방법 등의 내용을 보강해주신 점 감사드립니다.
참여자님의 기여 덕분에 문서의 완성도가 더욱 높아졌습니다.
내년도 Contribution에 참여해주신다면 감사드리겠습니다.
