### ISSUE TITLE
문서 상단에 Navigation 추가 검토

### ISSUE THREAD

**Issue by giant-hj** [eGovFramework/egovframe-docs#353]
MD 파일로 변환중인 전자정부 표준프레임워크 가이드 문서는 layer 별로 폴더링이 되어 있긴 하지만 같은 layer 내에서도 상하위 구조를 갖는 문서가 있습니다.

예) batch-core-step.md 
     └ batch-core-step_variable.md

예) batch-core-item_reader.md
     └ batch-example-db-jdbccursor.md
     └ batch-example-db-jdbcpaging.md
     └ batch-example-file-delimited.md
     └ ... 

md 파일로 변환된 문서의 링크를 따라다니다 보면 어느 내용에 대한 상세 설명인지 알기가 어렵습니다.

문서 상단에 Navigation 이 있으면 문서간의 상하위구조를 알 수 있고, 상위 문서로 빠르게 이동할 수 있는 장점이 있을 것 같습니다.

예) Spring Documents
![image](https://github.com/user-attachments/assets/92c263f7-368a-4124-b043-bad4bd8a3c46)
https://docs.spring.io/spring-framework/reference/core/beans/dependencies/factory-collaborators.html

감사합니다.

**Comment by eGovFrameSupport** [comment]
최초 Contribution시 문서간 상하위 계층의 문제를 인지하지 못했고, 그로 인해 참여자분들에게 적절한 가이드가 제공되지 않았습니다.
그래서 batch-layer에 대해서는 파일명에 "-"와 "_"를 구분함으로써 계층구조를 임시로 적용하였습니다.
내년도 Contribution에는 문서간 상하위 계층 문제에 대해 폴더 방식을 적용할지 혹은 위와 같은 파일명 방식을 적용할지 또는 다른 방식을 적용할지에 대한 결론을 내린 후 진행할 예정입니다.
혼란을 드린 점 사죄드리고, 좋은 의견 감사드립니다.
