### ISSUE TITLE
README 영문 추가

### ISSUE THREAD

**Issue by chocoPenguin** [eGovFramework/egovframe-docs#378]
README에 영문으로 내용이 추가되면 좋을 것 같습니다.
대부분의 사용자들은 한국인이겠지만, github 페이지를 방문한 다른 외국인들도 이 저장소를 간략하게 알려주면 좋을 것 같습니다.

**Comment by eGovFrameSupport** [comment]
영문 README에 대한 필요성에 동감합니다.
영문 README 적용을 긍정적으로 검토하겠습니다.
좋은 의견 감사드립니다.
