### ISSUE TITLE
Label 사용 활성화

### ISSUE THREAD

**Issue by chocoPenguin** [eGovFramework/egovframe-docs#400]
- Issue, PR을 등록할 때 label을 1개 이상 달도록 권고하면 좋을 것 같습니다.
  - 특히 Issue에 "good first issue"를 추가할 경우, github 홈페이지에서 검색 시 추천 알고리즘에 뜰 확률이 높아집니다. 더 많은 사람들이 해당 레포지토리에 작업할 수 있도록 도움이 될 수 있을 것 같습니다.
  - 레포지토리가 잘 관리되고 있다는 인상을 줄 수 있습니다.
  - Ex) github docs
![image](https://github.com/user-attachments/assets/59aed8ff-e21d-4f55-a1e4-dd53d5457fab)

**Comment by eGovFrameSupport** [comment]
PR의 경우 신규 문서 추가에 대한 것인지 기존 문서 수정에 대한 것인지 등을 Label로써 표시하면 좋을 것 같고,
Issues의 경우도 여러 장점이 있을 것으로 기대됩니다.
긍정적으로 검토하겠습니다.
좋은 의견 감사드립니다.
