### ISSUE TITLE
Label 종류 추가

### ISSUE THREAD

**Issue by chocoPenguin** [eGovFramework/egovframe-docs#401]
- Label 종류를 추가하면 좋을 것 같습니다.
  - 현재 레포지토리는 documentation인데, label에서 사실상 사용 가능한 라벨이 bug, documentation, duplicate 밖에 없습니다. 
  - 다음 label들이 추가되면 좋을 것 같습니다.(vuejs docs 레포지토리 참고하였습니다: https://github.com/vuejs/docs/labels)
    - style-improvement: Related to theme design and/or ux
    - content: Issues / PRs related to docs content
    - discussion: Topics to discuss that don't have clear action items yet
    - "state: awaiting-feedback": Needs more input before further actions can be taken
    - "state: blocked": A label for merge requests where work is blocked
    - "state: needs-changes": PR requires changes to proceed
    - "state: review": PR issued and under review

**Comment by eGovFrameSupport** [comment]
Label 종류에 대해 고민하고 있었는데, 바로 상세한 종류에 대한 의견을 주셔서 감사드립니다.
컨트리뷰션 참여에 깊은 감사의 말씀 드립니다.
