### ISSUE TITLE
질문입니다!

### ISSUE THREAD

**Issue by gogoleelee88** [eGovFramework/egovframe-docs#403]
풀리퀘스트 피드백 받아서 수정해서 올리면 그거는 다른 사람들 다 리뷰하고 다시 봐주시는 건가요?

**Comment by eGovFrameSupport** [comment]
피드백 반영한 수정본을 올려주신다면 올려주신 날의 익일 오전에 확인을 합니다. 구체적으로, PR들을 순차적으로 확인하기 전에 먼저 해당 수정본을 먼저 확인합니다.
답변이 늦어져서 죄송합니다.
컨트리뷰션 참여에 깊은 감사의 말씀을 드리고, 내년도 컨트리뷰션에도 참여 부탁드립니다.
감사합니다.
