### ISSUE TITLE
문법 검사 Action 추가

### ISSUE THREAD

**Issue by kangmsu322** [eGovFramework/egovframe-docs#404]
가이드를 작성/수정하다 보니 한국어/영어 오탈자도 꽤 있고 틀려도 commit에는 문제가 없어 merge 이후에 발견되는 경우도 있었습니다.

github marketplace에서 action으로 제공되는 한국어 문법 검사기(https://github.com/marketplace/actions/korean-grammar-check)를 도입하면 문법 정확도가 향상될 것 같습니다.

**Comment by eGovFrameSupport** [comment]
문법 검사기 안내 감사드립니다.
내년도 컨트리뷰션에 적용 여부를 검토해보겠습니다.
좋은 의견 감사드립니다.
